source 'https://rubygems.org'

gem 'rails', '3.2.11'
gem 'jquery-rails'

group :production do
	gem 'pg'
end

group :development, :test do
	gem 'sqlite3'
end

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'bootstrap-sass', '~> 2.2.2.0'
  gem 'paperclip', '~> 3.0'
  gem "masonry-rails", "~> 0.1.8"
  gem "faker", "~> 1.1.2"
  gem 'devise'


end
